-- Таблиця користувачів
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL DEFAULT 'USER'
);

-- Таблиця книг
CREATE TABLE books (
                       id BIGINT AUTO_INCREMENT PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       author VARCHAR(255) NOT NULL,
                       isbn VARCHAR(50),
                       publication_year INT
);

-- Таблиця коментарів (зв'язок Many-to-One до Users та Books)
CREATE TABLE comments (
                          id BIGINT AUTO_INCREMENT PRIMARY KEY,
                          text VARCHAR(2000),
                          created_at TIMESTAMP,
                          user_id BIGINT,
                          book_id BIGINT,
                          CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id),
                          CONSTRAINT fk_comments_book FOREIGN KEY (book_id) REFERENCES books(id)
);

-- Початкові дані
INSERT INTO users (username, password, role) VALUES ('admin', '$2a$10$uDzQ1z6B9PNeLoUj9sBMoeVGHV.ro0b/4gMqNg0x.PYX6K5bHA4LS', 'ADMIN');

INSERT INTO books (title, author, isbn, publication_year) VALUES ('Spring in Action', 'Craig Walls', '9781617294945', 2022);

INSERT INTO comments (text, created_at, user_id, book_id) VALUES ('Чудова книга! Дуже рекомендую.', CURRENT_TIMESTAMP(), 1, 1);
INSERT INTO comments (text, created_at, user_id, book_id) VALUES ('Трохи застаріла інформація, але цікаво.', CURRENT_TIMESTAMP(), 1, 1);